RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: mispmsgrule.yml
SQLITE3:
  path_file_db: "/sqlite3/sqlite3.db"
NATS:
  host: "192.168.9.208"
  port: 4222
  cache_ttl: 3600
  subscriptions:
    listener_case: "object.casetype.local"
    sender_command: "object.commandstype"
MISP:
  host: misp-center.cloud.gcm
THEHIVE:
  send: true
