RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: mispmsgrule.yaml
REDIS:
  host: "127.0.0.1"
  port: 6379
NATS:
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 3600
  subscriptions:
    sender_case: "object.casetype"
    listener_command: "object.commandstype"
MISP:
  host: misp-center.cloud.gcm
  auth: Z2PwRBdP5lFP7rdDJBzxmSahaLEwIvJoeOuwhRYQ
THEHIVE:
  send: true
