RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: mispmsgrule.yml
REDIS:
  host: "192.168.9.208"
  port: 6379
NATS:
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 3600
  subscriptions:
    sender_case: "object.casetype"
    listener_command: "object.commandstype"
MISP:
  host: "misp-world.cloud.gcm"
THEHIVE:
  send: false
