RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: mispmsgrule.yml
REDIS:
  host: "127.0.0.1"
  port: 6379
NATS:
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 3600
  subscriptions:
    listener_case: "object.casetype"
    sender_command: "object.commandstype"
MISP:
  host: misp-center.cloud.gcm
THEHIVE:
  send: true
