#    ORGANIZATIONS настройки организаций в MISP
#
# orgName - наименование организации в полях 'Организация-создатель' и
#  'Организация-владелец' MISP
# sourceName - наименование источника в json сообщении от TheHive
#
#    LOGGING настройки логирования
#
# msgTypeName - тип сообщения, от этого зависит в какой лог-файл будет отправлятся
#  сообщение, а также с каким префиксом оно будет дублироватся в консоль
# writingFile - нужно ли записывать сообщение в файл или только выводить в консоль
# writingStdout - нужно ли выводить сообщение в консоль
# pathDirectory - директория для записи лог-файлов
# maxFileSize - максимальный размер файла, после которого будет создаваться новый
#  файл, а текущий будет архивироваться
#
#    ZABBIX настройки подключения к серверу Zabbix
#
# networkHost: хост в формате ip или domainname для подклчения к серверу
#  networkPort: сетевой порт
#  zabbixHosts: группа хостов zabbix
#    - zabbixHost: имя хоста (приемник сообщений)
#      eventTypes: группы типов событий (например error, info или handshake)
#        - eventType: тип события (на какое событие отправлять данные)
#          zabbixKey: ключ приемника
#          isTransmit: триггер включения/отключения передачи
#          handshake:
#            timeInterval: временной интервал в минутах, нужен для
#             подтверждения активности модуля (если 0 НЕ ПЕРЕДАЮТСЯ)
#            message: сообщение которое будет отправлятся для подтверждения
#             активности (если пустое. то не передается)
#
ORGANIZATIONS:
  - { orgName: "GCM", sourceName: "gcm" }
  - { orgName: "CFO-RCM", sourceName: "rcmmsk" }
  - { orgName: "DFO-RCM", sourceName: "rcmkha" }
  - { orgName: "SFO-RCM", sourceName: "rcmnvs" }
  - { orgName: "SKFO-RCM", sourceName: "rcmsta" }
  - { orgName: "CR-RCM", sourceName: "rcmsr" }
  - { orgName: "PFO-RCM", sourceName: "rcmniz" }
  - { orgName: "UralFO-RCM", sourceName: "rcmsve" }
  - { orgName: "SZFO-RCM", sourceName: "rcmspb" }
  - { orgName: "KGD-RCM", sourceName: "rcmkgd" }
  - { orgName: "UFO-RCM", sourceName: "rcmros" }
  - { orgName: "SMOL-RCM", sourceName: "rcmlnx" }
LOGGING:
  - {
      msgTypeName: "error",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "warning",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "info",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "events",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "testing",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
ZABBIX:
  networkHost: "192.168.9.45"
  networkPort: 10051
  zabbixHosts:
    - zabbixHost: "test-uchet-db.cloud.gcm"
      eventTypes:
        # для отслеживания ошибок
        - eventType: "error"
          zabbixKey: "error_bav"
          isTransmit: true
          handshake:
            timeInterval: 0
            message: ""
        # для информационных сообщений о выполненной работе
        - eventType: "info"
          zabbixKey: "info_bav"
          isTransmit: true
          handshake:
            timeInterval: 0
            message: "I'm still alive"
        # для регулярного отстукивания что модуль еще работает
        - eventType: "handshake"
          zabbixKey: "handshake_bav"
          isTransmit: true
          handshake:
            timeInterval: 1
            message: "0"
