RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: mispmsgrule.yaml
REDIS:
  host: "192.168.9.208"
  port: 6379
NATS:
  host: nats.cloud.gcm
  port: 4222
MISP:
  host: misp-world.cloud.gcm
  auth: TvHkjH8jVQEIdvAxjxnL4H6wDoKyV7jobDjndvAo
THEHIVE:
  send: false
ElasticSearch:
  host: datahook.cloud.gcm
  port: 9200
  prefix: test
  index: thehive33
  name: elasticsearch
  authtype: basic
  user: writer
  passwd: 1zex3TvB
NKCKI:
  host: 127.0.0.1
  port: 12000
