RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: mispmsgrule.yaml
NATS:
  host: nats.cloud.gcm
  port: 4222
MISP:
  host: misp-center.cloud.gcm
  auth: Z2PwRBdP5lFP7rdDJBzxmSahaLEwIvJoeOuwhRYQ
ElasticSearch:
  host: datahook.cloud.gcm
  port: 9200
  prefix: test
  index: thehive33
  name: elasticsearch
  authtype: basic
  user: writer
  passwd: 1zex3TvB
NKCKI:
  host: 127.0.0.1
  port: 12000