LOGGING: 
  - { msgTypeName: "error", writingFile: true, pathDirectory: "logs", writingStdout: false, maxFileSize: 1024 }
  - { msgTypeName: "info", writingFile: true, pathDirectory: "logs", writingStdout: true, maxFileSize: 1024 }
