RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: mispmsgrule.yaml
REDIS:
  host: "127.0.0.1"
  port: 6379
NATS:
  host: nats.cloud.gcm
  port: 4222
MISP:
  host: misp-center.cloud.gcm
  auth: Z2PwRBdP5lFP7rdDJBzxmSahaLEwIvJoeOuwhRYQ
THEHIVE:
  send: true
