RULES_PROC_MSG_FOR_MISP:
  directory: rules
  file: procmispmsg_test.yaml
NATS:
  host: nats.cloud.gcm
  port: 4222
MISP:
  host: misp-world.cloud.gcm
  port: 8181
  auth: TvHkjH8jVQEIdvAxjxnL4H6wDoKyV7jobDjndvAo
ElasticSearch:
  host: 192.168.13.3
  port: 9200
NKCKI:
  host: 127.0.0.1
  port: 12000